myproject/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls'))
]

myproject/demo/panel/urls.py
from django.urls import path
from panel import views

app_name = "panel"

urlpatterns = [
    path('', views.home, name = "home"),
    path('list/', views.list, name = "list"),
    path('edit/<int:pk>/', views.edit, name = "edit"),
    path('delete/<int:pk>/', views.delete, name = "delete")
]

myproject/demo/panel/models.py
from django.db import models

class Person(models.Model):
	first_name = models.CharField(null=False,blank=False,max_length=250)
	last_name = models.CharField(null=False,blank=False,max_length=250)
	email = models.CharField(null=False,blank=False,max_length=250)

myproject/demo/panel/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.urls import reverse
from panel.models import Person
# Create your views here.
def home(request):
    if request.POST:
        person = Person(
            first_name = request.POST['first_name'],
            last_name = request.POST['last_name'],
            email = request.POST['email'])
        person.save()
        import pdb
        pdb.set_trace()
    return render(request, 'panel/home.html', locals())


def list(request):
    persons = Person.objects.all()
    return render(request, 'panel/list.html', locals())
 
def edit(request, pk):
    
    person = Person.objects.filter(pk= pk).first() # get(pk)
    if request.POST:
        person.first_name = request.POST['first_name']
        person.last_name = request.POST['last_name']
        person.email = request.POST['email']
        person.save()
    return render(request, 'panel/home.html', locals())

def delete(request, pk): 
    person = Person.objects.get(pk = pk) # get(pk)
    person.delete()
    return redirect(reverse('panel:list'))

myproject/demo/panel/templates/panel/home.html
<html>
    <h1>
        Ingrese su usuario
    </h1>

    <form action="." method="post">
		{% csrf_token %}
		
		<hr>
		<!-- {{errors}} -->
		<div>
			<label>Nombre</label>
			<input type="text" name="first_name" {%if person %} value="{{person.first_name}}" {% endif %} required>
		</div>
		<div>
			<label>Apellidos</label>
			<input type="text" name="last_name" {%if person %} value="{{person.last_name}}" {% endif %} required>
		</div>
		<div>
			<label>Correo</label>
			<input type="email" name="email" {%if person %} value="{{person.email}}" {% endif %} required>
		</div>
		<div>
			<button type="submit">Enviar</button>
		</div>
	</form>
</html>

myproject/demo/panel/templates/panel/list.html
<h1>lista de personas</h1>
	<ul>
		{% for p in persons %}
		<li>{{p.first_name}} - {{p.last_name}} - {{p.email}} - <a href="{% url 'panel:edit' p.pk %}">Editar</a> <a href="{% url 'panel:delete' p.pk %}">Eliminar</a> </li>
		{% endfor %}		
	</ul>